name: library-management
services:
  postgres:
    image: postgres:17.5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: library_management
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - local
    command: >
      postgres -c shared_buffers=512MB
               -c work_mem=16MB
               -c maintenance_work_mem=128MB
               -c effective_cache_size=1GB
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d library_management" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

volumes:
  postgres_data:

networks:
  local:
